name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. משיכת הקוד
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. אימות Keyless מול Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/252873823435/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@esh27-unicorn-core.iam.gserviceaccount.com'

      # 3. התחברות ל-Artifact Registry
      - name: Set up Docker Auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 4. בניית ה-Docker ע"י שרתי GitHub
      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/esh27-unicorn-core/esh27-repo/backend:${{ github.sha }} -t us-central1-docker.pkg.dev/esh27-unicorn-core/esh27-repo/backend:latest .

      # 5. דחיפה ל-Artifact Registry
      - name: Push to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/esh27-unicorn-core/esh27-repo/backend:${{ github.sha }}
          docker push us-central1-docker.pkg.dev/esh27-unicorn-core/esh27-repo/backend:latest

      # 6. פריסה ישירה ל-Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: esh27-core-backend
          image: us-central1-docker.pkg.dev/esh27-unicorn-core/esh27-repo/backend:${{ github.sha }}
          region: us-central1
          flags: '--allow-unauthenticated --port=8080'
